import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"

import {
  ClerkProvider,
  SignInButton,
  SignedOut,
} from '@clerk/nextjs'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
    <body>
          <SignedOut>
            <SignInButton />
          </SignedOut>
          {children}
        <Toaster />
        </body>
    </html>
    </ClerkProvider>
  );
}
